### ISSUE TITLE
Packaging json2typescript as a part of a library

### ISSUE THREAD

**Issue by vinaysoni** [dhlab-basel/json2typescript#10]
Hi, 

Appreciate your work on json2typescript. It is great!

I can  make json2typescript work in my UI project (an end-user project) successfully and love it. However, when I try to package it as a part of a library (like ng2utils), it fails with this error:

**_"Error at /home/vin/dev/ang/ng2utils/node_modules/json2typescript/src/json2typescript/json-convert.ts:13:5: Public static property 'ValueCheckingMode' of exported class has or is using private name '(Anonymous class)'."_**

I am trying to use json2typescript as a part of my github/npm library project called "ng2utils". I am packaging it using: gonzofish/angular-library-set

I have fixed it (temporarily) by changing ValueCheckingMode from an Inner class to an independent class) and copying the source in my project. This is however not to my liking as I would rather point to your project.

Is there an alternative fix to take care of this issue? Please let me know if any part of my question is not clear.

Thanks!

**Comment by andreas-aeschlimann** [comment]
What Angular version are you using? We used to have problems with this exact property type when working with Angular <2.1 if I remember correctly.

**Comment by savanvadalia** [comment]
I think this issue is related to the typescript version and not the angular, I get the same error on one of my project which uses typescript 2.2.1 but I don't get this error on a project which has typescript version 2.3.4.

I agree with @vinaysoni  its better to put the ValueCheckingMode outside of the JsonConvert Class. 
Also I would suggest to use typescript enum syntax which serves the same purpose and it will resolve this error permanently irrespective of the typescript versions. 

```
export enum ValueCheckingMode {
    ALLOW_NULL = 1,
    ALLOW_OBJECT_NULL = 2,
    DISALLOW_NULL = 3
}
```

**Comment by andreas-aeschlimann** [comment]
I don't understand. According to my info it should be possible from TypeScript 1.6 to have a static class as a member of another class.

**Comment by andreas-aeschlimann** [comment]
Fixed in the new version with enums.

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
