### ISSUE TITLE
Throw error if a property is not set to undefined

### ISSUE THREAD

**Issue by savanvadalia** [dhlab-basel/json2typescript#13]
Hi

Loving the strict type checking of this library.  
Also when the debugMode is ON it really throws out some nice useful errors + messages.

I understand the library requirement for the mapping to work properly we need to initialize the map property as "undefined". But sometimes it is easy to miss out that part and you spend time to investigate what went wrong.

Is it possible to have a check within lib before the mapping procedure starts that if property has a decorator "@JsonProperty" it must have the value as "undefined". If not it throws an error.

If these extra check is affecting the overall performance of the library  I wouldn't mind if the check is only done when the debugMode is ON.

**Comment by andreas-aeschlimann** [comment]
To be honest I don't know how to answer that. The problem is that with no assignment of a value (including null or undefined), the variable is non-existent to the type-checker. 

If someone knows a solution, I would be happy to implement it. Because this is indeed a possible source of error.

**Comment by savanvadalia** [comment]
Was playing around a bit with lib functions I found in the `deserializeObject` method you use Object.Keys which returns only initialized properties.

```
        // Loop through all initialized class properties
        for (const propertyKey of Object.keys(classInstance)) {
            JsonConvert.deserializeObject_loopProperty(classInstance, propertyKey, jsonObject);
        }
```

But mapping array  in the `deserializeObject_loopProperty` method returns all properties which has decorator @JsonProperty
```
        // Get the mapping array
        let mapping = classInstance["__jsonconvert__mapping__"];
```

Would it be possible to filter out properties which are not initialized as `undefined` by finding the difference between the mapping array and Object.keys array and then error out those properties?

**Comment by andreas-aeschlimann** [comment]
Indeed it would be possible to define all properties just in the mapping variable. I will think about it when looking at the project tomorrow.

**Comment by andreas-aeschlimann** [comment]
I looked into it but I cannot seem to find a good solution.

1) When the decorator of a property is run, the value of the property is always undefined, even if you give it a value in your class. It looks like the value is assigned after the decorator is called.

So after my investigation it's pretty obvious that the automatic "reminder" to assign a property is not possible.

2) We cannot use  classInstance["__jsonconvert__mapping__"] because of class inheritation. Example: When you have a class `Animal`, a class `Cat` extending `Animal` and a class `Dog` extending `Animal` with different properties, then the decorator will save the info to the base class. The function `Object.keys()` is the proper way to check whether a property really belongs to `Dog` or `Cat`.

There sure is a bypass for this issue, but it could get very ugly if you want to follow down the way of 2.

**Comment by savanvadalia** [comment]
@andreas-aeschlimann, Thanks for looking into this. 
 I do use class inheritance within my typescript-json objects. 

If there is no proper solution I am happy to be the current way as it is more of a nice to have feature.

Again thanks for trying and keep up the great work with this awesome lib 👍

**Comment by andreas-aeschlimann** [comment]
Closed due to the fact that reflection is the only proper solution afaik.

The pull request solves that, but we decided not to implement it in order not to get a dependency.
