### ISSUE TITLE
Why construct a new JsonConvert, why not make deserialize / serialize static methods?

### ISSUE THREAD

**Issue by theBull** [dhlab-basel/json2typescript#28]
Is there a reason behind this? Perhaps it's not an issue so much as wanting to understand if there's a more efficient way to use the library, is the following not possible for a reason precluded by implementation detail?

```
import { JsonConvert } from 'json2typescript';

// ...

let user = JsonConvert.deserialize({}, User);
```

Great job on the tool, I hope my question doesn't come across as ignorant :).

**Comment by andreas-aeschlimann** [comment]
Your question is indeed good and the answer is partially in the thread #14.

There are people that want to use different settings in for the JsonConverter in the same application. Before the current update, all properties and methods were static. Then these people were forced to set the properties after every call, which is not very clean.

Other libraries like JsonConvert in .NET do it statically as well, and you have to pass your settings with a function call. That's why I originally implemented it like this as well.

In the end, it's a question of preference, but I think the instance approach is nicer, because you can always just store an instance statically in your app. In my application, I have a class "api.service.ts", and at some point I define there `static jsonConvert: JsonConvert" and that's all I need. I also thought about adding a helper property to the JsonConvert class, so people could even use something like `JsonConvert.instance` or something like that.

**Comment by theBull** [comment]
Excellent, makes perfect sense. After using your library to do some deserialization, I ran into the case you're talking about where I wanted to set the `ALLOW_NULL` flag on the instance and decided it would be useful to create a static reference to `JsonConvert` in a wrapper class, as you did for your api.service.ts. So I actually do like the ability to have either an instance of JsonConvert or the flexibility to create my own wrappers as needed. Thanks for your response!

**Comment by andreas-aeschlimann** [comment]
No worries.

If you have further input, let me know.
