### ISSUE TITLE
Answer to deserialize(null) is not as expected

### ISSUE THREAD

**Issue by andreas-aeschlimann** [dhlab-basel/json2typescript#33]
Note to myself: Look into the response of (de)serializing undefined or null

**Comment by Cecilya** [comment]
I'm bumping this because I just spent 2 hours trying to find out why my property marked as optional was throwing an error on deserialising when it wasn't present - only to find out that it was present with a null value which is apparently different than "not present at all". The reason ("Given value is null.") doesn't explain the difference between the expected behaviour, namely all non-values (undefined, null, property not present) deserialising normally, and the actual behaviour, namely only undefined and property not present deserialising normally.
I think a simple note along the lines of "explicit null values are treated as value, not as empty values" in the deserialisation message would already help.

**Comment by andreas-aeschlimann** [comment]
Interesting. But yes, null values are treated as values. Optional means, as you said, that if it is present, it has to match the given type.

It doesn't necessarily throw an exception then. It depends, whether you allow null values. If you use the mode `ValueCheckingMode.ALLOW_NULL`, json2typescript will allow what you want. But then null is always allowed for all properties.

**Comment by Cecilya** [comment]
Thanks for the quick reply! I think including info on the `ValueCheckingMode` in the error message would also be helpful, but a general mention of the treatment of null values would definitely improve debuggability.

The `ValueCheckingMode` can only be set globally, correct? It might be interesting to allow or disallow null values for different objects, e.g. depending on which external API returns them. At the moment I'm fixing my own API so null isn't returned, though, so I don't need the feature right now.

**Comment by andreas-aeschlimann** [comment]
Yes, I will note it down.

The checking mode is set per instance of `JsonConvert`. You can set up multiple instances for different objects, if you want to. Or you can write a wrapper that changes the checking mode before doing requests for certain objects.

**Comment by Cecilya** [comment]
Oh, that sounds very useful! I'll keep it in my should I ever need it.

**Comment by andreas-aeschlimann** [comment]
In general I would still recommend to use JsonConvert as a singleton, it's easier to just have one instance of it in the whole project.

There is an actual reason why we decided to treat `null` not the same as not present. `null` is often used in databases when no relation is wanted. But it still can mean that the user has selected not to have a relation, while removing the property could mean that the relation has not been defined yet:
- null = chosen not to have a relation
- int = foreign key id
- undefined/non-present = not chosen yet

**Comment by andreas-aeschlimann** [comment]
This problem should be fixed, see also #69.
