### ISSUE TITLE
Differences with the "class-transformer" library.

### ISSUE THREAD

**Issue by electrotype** [dhlab-basel/json2typescript#48]
Hi,

(I don't know if this kind of post is allowed here. Feel free to delete it if it's not!)

I'm working on a Typescript project and I need a way to convert a Json/Plain object to a class based object.

I see there is a library called _class-transformer_ which seems to be similar to _json2typescript_. Both seem active.

Are there differences between the two or are they interchangeable options? 
Does someone have experience with both?

Thanks for any feedback.

**Comment by andreas-aeschlimann** [comment]
The other library uses a different approach to verify with the data. We have still open pull requests that go into a similar direction, but as of now our library does _not_ have any dependencies. I don't know about the impact of importing `reflect-metadata` - which is a nice library by the way - but you will need that for `class-transformer`.

I don't know about `class-transformer`, but `json2typescript` is quite helpful when debugging errors in JSON or TypeScript. That helps a lot when working on new projects. Otherwise, both projects look quite similar for development.
