### ISSUE TITLE
Wrong classes being used with deserializeObject when ran with ng build -prod

### ISSUE THREAD

**Issue by jturner** [dhlab-basel/json2typescript#51]
We have a number of "steps" that included settings. Each step has something like

```typescript
import { Step } from './Step'
import { Setting } from './MySetting'

@JsonObject
export class MyStep extends Step {
	@JsonProperty('settings', [Setting], true)
	settings?: Setting[] = [];
}
```

We are using jsonConvert.deserializeObject to convert json into a Step. However when building with ng build -prod every Step with a Setting seems to be using the first Setting class it finds, not the Setting actually imported in the correct Step.

We only see this behavior with -prod.

**Comment by andreas-aeschlimann** [comment]
Chance is high that you have a circular dependency. As noted in the ReadMe, you have to make sure that no circular dependencies occur.

I had the same issue: It worked in development, but not in production.

**Comment by andreas-aeschlimann** [comment]
Due to inactivity, I'm going to close this issue.

**Comment by emirbega** [comment]
@andreas-aeschlimann I think this issue is still present and it has to do with Uglify mangle option. See screenshots for prod and non prod builds and you will see the issue.
<img width="1112" alt="Screenshot 2019-04-27 at 00 23 48" src="https://user-images.githubusercontent.com/27885681/56839768-5c98cb80-6884-11e9-8f40-cb3a45f3f13d.png">
<img width="1361" alt="Screenshot 2019-04-27 at 00 28 09" src="https://user-images.githubusercontent.com/27885681/56839769-5c98cb80-6884-11e9-8b74-a01eb680af15.png">

**Comment by andreas-aeschlimann** [comment]
Did you try to use the `@JsonObject("className")` decorator? This should fix/bypass this problem. This fix has been released a few months ago, see also the current ReadMe!
