### ISSUE TITLE
Custom converters

### ISSUE THREAD

**Issue by gempain** [dhlab-basel/json2typescript#6]
Hello,

First let me thank you for this amazing project. It works well, and the error logging is incredibly accurate and informative. I have rarely seen a library designed and implemented with such care and rigor.

The only missing feature, which would make it perfect, is the ability to set custom converters. May be it's already implemented and I haven't seen it in the docs. Another JSON mapper library for TypeScript has that feature (implemented but not documented): https://github.com/jf3096/json-typescript-mapper. May be you could get some inspiration from there ?

I might try to implement something and send a pull request but I can't promise anything in the following weeks.

All the best !

**Comment by andreas-aeschlimann** [comment]
Hey @gempain, interesting point. Can you provide a few code examples how this converter could work? I think I know what you mean, but just to make sure. :-)

**Comment by gempain** [comment]
Hey @andreas-aeschlimann ,

Well, you're on the right path. But the converter should be typed, and we also need a serializer. In my previous post I forgot to mention the use cases where this feature would be useful. Imagine you want to work with types other than String, Number, Boolean or Date (is don't think Date is supported in the current version, but forgive me if I am wrong), for example let's say you want to use Moment in place of Date objects. I would expect setting a custom converter that tells the mapper how to serialize and/or deserialize a certain property.

In [json-typescript-mapper](https://github.com/jf3096/json-typescript-mapper), they have defined an interface called [`ICustomConverter`](https://github.com/jf3096/json-typescript-mapper/blob/a4f08973a7aeb1c50753687009949f58a44ee10c/index.d.ts):
```
/**
 * When custom mapping of a property is required.
 *
 * @interface
 */
export interface ICustomConverter {
    fromJson(data: any): any;
    toJson(data: any): any;
}
```

I think their interface misses genericity to take advantage of TypeScript features, and I am not a fan of the `I`, so after a bit of refactoring, you'd get something like this:
```
export interface CustomConverter<T> {
    deserialize(data: any): T;
    serialize(data: T): any;
}
```

Now, let's see it in action:
```
import {Moment} from "moment";

class MomentConverter implements CustomConverter<Moment> {
    deserialize(data: any): Moment {
      let m = moment(data);
      return m.isValid() ? m : data; // *1
    }
    serialize(data: Moment): any {
      return data; // *2
    }
}

@JsonObject
export class Product {

    @JsonProperty("creationDate", Moment, MomentConverter)
    public creationDate: string = undefined;
    
    @JsonProperty("purchaseDate", Moment, MomentConverter)
    public purchaseDate: Moment = undefined;
    
}
```

Notes:
- `*1` Deciding on the return value could be the subject of a debate. Would you return `undefined`, the original data, or throw an error if the type if not as expected ? I think the person that implements the converter should be the one deciding.
-  `*2` If I am right, the serialize function returns a JSON object, not a string. That obejct can be serialized via the native `JSON.stringify` method. In the particular use case I chose, `Moment` objects have embedded JSON serialization methods similar to those for native `Date` objects. That's why I return the moment directly, but obviously you could return a date formatted String, or a `Date` with `data.toDate()`.

Looking forward to see how this will be used !

All the best;

**Comment by andreas-aeschlimann** [comment]
It looks interesting, I will certainly will look into it in details when I have time.

`*1` The deserializer must return the type that is given, or null (if allowed in json2typescript). After all, json2typescript is here to force you to be strict on the API side. If your custom converter fails, there must be something wrong which you should correct and an exception should be thrown.

`*2` Serialize should be just JSON.stringify I guess, so return a string.

**Comment by gempain** [comment]
Agree 100% !

**Comment by andreas-aeschlimann** [comment]
I will look into this soon. At the moment I am busy with another project, so it will take some time.

I will keep this thread open until I finished it!

**Comment by andreas-aeschlimann** [comment]
After making some tests and putting some thoughts into it, I see two options how to implement the custom converter:

1) Extend the current decorator `@JsonProperty` and make it allow the converter interface as second parameter as the type instead. Your example above

`@JsonProperty("creationDate", Moment, MomentConverter)`

makes no sense in my eyes because the expected type (here: `Moment`) is obsolete, and the third parameter is currently used already. Instead, we could do something like this:

`@JsonProperty("creationDate", MomentConverter)`

This approach is easy to use, but has one big downside: 

Somewhere in the code I will need to make IF/ELSE and check if the second parameter is a custom converter or a type (class) as usual. 

I think there is no proper way in TypeScript to find out what this parameter is. I can only check if the methods deserialize/serialize exist which should be an indication that it is actually a custom converter derived from the interface.

But what if you actually have a type that contains the functions `deserialize` and `serialize`? I think this could cause a conflict.

Do you have an idea how to make a workaround for this?

2) We could use the mapper as fourth parameter 

`@JsonProperty("creationDate", Moment, false, MomentConverter)`

but this would be ugly too, as expectedType (here: `Moment`) is obsolete and isOptional is usually false anyway.

3) We could introduce a second decorator @Blabla(CustomConverter) which can be used for all properties needing custom converters. This decorator could replace the original @JsonProperty or expand it.

**Comment by gempain** [comment]
In typescript there is currently no way to determine reliably the name of a class. The only unreliable way I know is to use `obj.constructor.name`.

I think we should keep `@JsonProperty` and pass the converter as second argument. To differentiate types from converters, we could introduce a new annotation `@Converter`.
```
@Converter
class MyConverter implements Converter {
    // serialize and deserialize implementations
}

@JsonProperty('myProp', MyConverter)
```
With that annotation, you can easily check if the second argument is a converter.

Obviously, this is not perfect as you both annotate the converter `@Converter` and implement `Converter`, which is redundant. So far I don't know of a better way, but I'll keep thinking about it.

**Comment by andreas-aeschlimann** [comment]
I liked your idea, but it causes issues when you forget the `@Converter` decorator. One could say, it's the developer's problem. On the other hand, I would like to give good debugging information which is not possible like that. 

If you forget the decorator instead of the class `MyConverter`, the code has to assume it is a type you want to map. This will lead to failure of the whole serialization/deserialization and might confuse developers because we cannot tell them whats wrong. It will only say that the serialization/deserialization to/from `MyConverter` failed.

I will think about it for a little more and then make a decision. Things coming to my mind are:
- use abstract class instead of interface (then check is possible I think)
- use another property decorator

**Comment by andreas-aeschlimann** [comment]
I went with the converter decorator and the `@JsonProperty` decorator.

The confusion may still happen, but I added some smart error message when the case I described would appear.

**Comment by gempain** [comment]
Thanks for the feature ! I will have a look at it when I have some time, and give you some feedback :)

**Comment by andreas-aeschlimann** [comment]
Sure thing. I'm currently updating the README because there are quite some changes.

I'm not a fan of breaking changes, but I couldn't bypass them with the change to `JsonConvert` instances.

**Comment by gempain** [comment]
Agree, but sometimes you have to come out with a major release and I feel like this one is :)

**Comment by andreas-aeschlimann** [comment]
Hopefully. I'm looking forward to your feedback.

I have checked out the GitHub code and used `npm link` to reference it. It worked quite well, but I dunno about the guys with the enum/JS problems (from ionic I think).

**Comment by andreas-aeschlimann** [comment]
Hello, please provide a non-working minimal example. I often used nested objects of a level of 5 or more without any issues. There are no custom converters necessary for that in general.

**Comment by MDSpandanaJMJ** [comment]
@JsonObject
export class Resource {

    @JsonProperty('@id') _id: string = undefined;
    @JsonProperty('@type') _type: string = undefined;
    @JsonProperty('id') _resourceId: string = undefined;
    @JsonProperty('description') _description: string = undefined;
    @JsonProperty({jsonKey: 'Attribute', expectedJsonType: [Attribute]}) _attribute: Attribute[] = undefined;
    @JsonProperty('connectedTo') _connectedTo: string = undefined;


    constructor(id: string, type: string, resourceId: string, description: string, attribute: Attribute[], connectedTo: string) {
        this._id = id;
        this._type = type;
        this._resourceId = resourceId;
        this._description = description;
        this._attribute = attribute;
        this._connectedTo = connectedTo;
    }
}

So this is how my template looks like. I defined the Attribute object which as other nested types. There is a three level nesting. The first level do get serialized. However, they fail when it comes to the deseriazling attribute array. Not sure if it is has something to do with my json object.

**Comment by andreas-aeschlimann** [comment]
I don't think you can use a constructor that way because `json2typescript` calls the constructor with no arguments. It will probably set all your properties to undefined because of that.

Try your code without constructor (or comment everything out).

**Comment by andreas-aeschlimann** [comment]
You probably have some other issue because this is not possible.

For example, it could be a conflict of classes. Are you sure that you import the correct class "Resource", for example?

If you can post me a small example to GitHub which I can launch with Angular CLI, I can try to help you.

**Comment by MDSpandanaJMJ** [comment]
Looks like I am progressing on this. I have to verify the templates. If not I will post it on GitHub. Since I have an NDA i couldn't do it at present. I will try to modify it and post if it doesn't work. I really appreciate your help. Thank you!

**Comment by MDSpandanaJMJ** [comment]
They are failing when I have an array of objects which are at nested level: 
Is there any way of specifying this. Right now I am using the below way;
@JsonProperty('Attribute', [Attribute])
    _attribute: Attribute[];  

And below is my error:
Error: Fatal error in JsonConvert. Failed to map the JSON object to the JavaScript class "Resource" because of a type error.

	Class property: 
		_attribute

	Expected type: 
		[Attribute]

	JSON property: 
		Attribute

	JSON type: 
		[object,object,object,object,object,object,object,object,object,object,object,object]

**Comment by andreas-aeschlimann** [comment]
Is this all the error? Sometimes there is more above or after it.

I can't see a problem here, it should work.

**Comment by MDSpandanaJMJ** [comment]
So, it says that deserialization is not happening due to type mismatch.
These are the two errors being displayed:
===================
Error: Fatal error in JsonConvert. Failed to map the JSON object to the JavaScript class "Resource" because of a type error.
=======================
core.js:1350 ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_attribute' of undefined
TypeError: Cannot read property '_attribute' of undefined

**Comment by andreas-aeschlimann** [comment]
You have to compare your Attribute class to your actual JSON object. There is something not matching there.

**Comment by MDSpandanaJMJ** [comment]
So this is how my json looks and each Aspect itself is an array of that type. And this is how I defined my classes. Do you say that it should have keys on all internal objects?
"Attribute": [{
  "Aspect":[ ],
  "name": "...",
 "description":"..."
},
{
 "Aspect":[ ],
  "name": "...",
 "description":"..."
},
{
 "Aspect":[ ],
  "name": "...",
 "description":"..."
}
]

**Comment by andreas-aeschlimann** [comment]
I can't tell from these fragments, can you provide a minimal non-working example in GitHub?

**Comment by MDSpandanaJMJ** [comment]
So, this got resolved. I noticed that there are some optional types in the json and I have to declare that flag explicitly. However, while deserializing if I am getting an array of objects, I don't see a direct way of specifying the class type. For example if I get Attribute[] from the back end, and adding jsonConvert.deserialize(response[0], [Attribute]); or jsonConvert.deserialize(response[0], Attribute[]) are giving me errors.
Is there a particular way to deserialize arrays?

**Comment by andreas-aeschlimann** [comment]
You can use jsonConvert.deserializeArray(data, Attribute) if your json matches the type of an array of Attribute. The method jsonConvert.deserialize(data, Attribute) does the same because it intelligently picks the appropriate case (flat object/array).
