### ISSUE TITLE
[Question] deserialize a null object should return null or error?

### ISSUE THREAD

**Issue by jmesa-sistel** [dhlab-basel/json2typescript#69]
Hello
This code 
` new JsonConvert().deserialize(null, MyClass);`
thows an error, is this intended?

I think it should return null, but it is my opinion

**Comment by andreas-aeschlimann** [comment]
It is indeed a bug, as already mentioned in #33. I will fix it this summer when updating the library.

**Comment by andreas-aeschlimann** [comment]
As of v1.0.6, this will be changed.

If `ValueCheckingMode` is set to `DISALLOW_NULL`, then
- jsonConvert.serialize(null) throws an error
- jsonConvert.serialize(undefined) throws an error
- jsonConvert.deserialize(null, AnyClass) throws an error
- jsonConvert.deserialize(undefined, AnyClass) throws an error

If `ValueCheckingMode` is set to something else as `DISALLOW_NULL`, then
- jsonConvert.serialize(null) returns null
- jsonConvert.serialize(undefined) returns null
- jsonConvert.deserialize(null, AnyClass) returns null
- jsonConvert.deserialize(undefined, AnyClass) throws an error, because undefined is not a valid JSON object
