### ISSUE TITLE
Feature request: supporting generics

### ISSUE THREAD

**Issue by onimoger** [dhlab-basel/json2typescript#8]
First thank you for a nice library.

I would like to get this working with generics. Example in code:
```
@JsonObject
export class Root<T> {
  @JsonProperty('id', Number)
  id: number = 0;
  @JsonProperty('child', T)
  child: T = undefined;
}

@JsonObject
export class ChildA {
  @JsonProperty('a', String)
  a: string = undefined;
}

@JsonObject
export class ChildB {
  @JsonProperty('b', Number)
  b: number = 0;
}

let a = JsonConvert.deserializeObject(r.json(), Root<ChildA>);
let b = JsonConvert.deserializeObject(r.json(), Root<ChildB>);
```
Is this somehow possible?

**Comment by andreas-aeschlimann** [comment]
I am no expert, but if I am right you cannot use the generic T in any other way than a type hint in TypeScript. I had a similar issue somewhere else and I think I couldn't make it work.

We should absolutely investigate it because it would be a nice feature.

**Comment by andreas-aeschlimann** [comment]
I am going to close this issue, because I am pretty sure it will not be possible to use generics. The main problem is that on JavaScript runtime, generics do not exist. In fact, it is just type hinting before compile time for the developer.

Also, the way how json2typescript is implemented, it cannot support generics.
